name: run-tests

on:
  push:
    branches: [main, develop, test]
  pull_request:
    branches: [main, develop, test]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.1]
        laravel: [9.*]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 9.*
            testbench: 7.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_ENV: ${{ secrets.APP_ENV }}
          CACHE_DRIVER: ${{ secrets.CACHE_DRIVER }}
          FILESYSTEM_DISK: ${{ secrets.FILESYSTEM_DISK }}
          VIVA_WALLET_ENV: ${{ secrets.VIVA_WALLET_ENV }}
          VIVA_WALLET_MERCHANT_ID: ${{ secrets.VIVA_WALLET_MERCHANT_ID }}
          VIVA_WALLET_API_KEY: ${{ secrets.VIVA_WALLET_API_KEY }}
          VIVA_WALLET_CLIENT_ID: ${{ secrets.VIVA_WALLET_CLIENT_ID }}
          VIVA_WALLET_CLIENT_SECRET: ${{ secrets.VIVA_WALLET_CLIENT_SECRET }}
          VIVA_WALLET_PAYMENT_SOURCE_CODE: ${{ secrets.VIVA_WALLET_PAYMENT_SOURCE_CODE }}
